### ISSUE TITLE
How to increase action rate for KongBlitz?

### ISSUE THREAD

**Issue by djwhatle** [konveyor/kube-kong-operator#23]
Right now I have 100 secrets and have KongBlitz set up to perform label updates. 

**My issue**: It seems like the label update communication with k8s happens very quickly (over the course of ~10 seconds I see 100 resource changes in `oc get secret --watch`) but there are a bunch of other tasks running as part of KongBlitz that make the actual time between these batches of requests at least a minute apart, maybe two minutes apart.

This means that the effective rate of requests isn't as high as I was hoping. I'm wondering if there are ways to run KongBlitz in a more lean mode where it just runs the core "update label" loop over and over.

**KongBlitz**
```
apiVersion: konveyor.openshift.io/v1alpha1
kind: KongBlitz
metadata:
  name: example-kongblitz
  namespace: king-kong
spec:
  perform_actions: true

  kongarmy_resources:
    actions:
    - label
    time_delta: 2

```

**KongArmy**
```
apiVersion: konveyor.openshift.io/v1alpha1
kind: KongArmy
metadata:
  name: example-kongarmy
  namespace: king-kong
spec:
  teardown: false

  requested_resources:
    - kind: Secret
      count: 100
```
